// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commodity.proto

package chiw.spc.proto;

public final class CommodityPB {
  private CommodityPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CacheType_CommodityMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CacheType_CommodityMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017commodity.proto\022\tCacheType\"M\n\014Commodit" +
      "yMsg\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005price\030" +
      "\003 \001(\001\022\024\n\014remainingQty\030\004 \001(\001B\037\n\016chiw.spc." +
      "protoB\013CommodityPBP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CacheType_CommodityMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CacheType_CommodityMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CacheType_CommodityMsg_descriptor,
        new java.lang.String[] { "Id", "Name", "Price", "RemainingQty", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
