// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: country.proto

package chiw.spc.proto;

public final class CountryPB {
  private CountryPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcountry.proto\022\tCacheType*.\n\nCountryMsg" +
      "\022\010\n\004None\020\000\022\006\n\002JP\020\001\022\006\n\002SG\020\002\022\006\n\002US\020\003B\035\n\016ch" +
      "iw.spc.protoB\tCountryPBP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
