// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: country.proto

package chiw.spc.proto;

/**
 * Protobuf enum {@code chi.base.proto.CountryMsg}
 */
public enum CountryMsg
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>None = 0;</code>
   */
  None(0),
  /**
   * <code>JP = 1;</code>
   */
  JP(1),
  /**
   * <code>SG = 2;</code>
   */
  SG(2),
  /**
   * <code>US = 3;</code>
   */
  US(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>None = 0;</code>
   */
  public static final int None_VALUE = 0;
  /**
   * <code>JP = 1;</code>
   */
  public static final int JP_VALUE = 1;
  /**
   * <code>SG = 2;</code>
   */
  public static final int SG_VALUE = 2;
  /**
   * <code>US = 3;</code>
   */
  public static final int US_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CountryMsg valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CountryMsg forNumber(int value) {
    switch (value) {
      case 0: return None;
      case 1: return JP;
      case 2: return SG;
      case 3: return US;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CountryMsg>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CountryMsg> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CountryMsg>() {
          public CountryMsg findValueByNumber(int number) {
            return CountryMsg.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return chiw.spc.proto.CountryPB.getDescriptor().getEnumTypes().get(0);
  }

  private static final CountryMsg[] VALUES = values();

  public static CountryMsg valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CountryMsg(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:chi.base.proto.CountryMsg)
}

