// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package chiw.spc.proto;

public final class OrderPB {
  private OrderPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chi_base_proto_OrderMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chi_base_proto_OrderMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\016chi.base.proto\032\rcountry.p" +
      "roto\032\017commodity.proto\"\320\002\n\010OrderMsg\022\017\n\002id" +
      "\030\001 \001(\tH\000\210\001\001\022\025\n\010quantity\030\002 \001(\005H\001\210\001\001\022\022\n\005pr" +
      "ice\030\003 \001(\002H\002\210\001\001\0224\n\tcommodity\030\004 \001(\0132\034.chi." +
      "base.proto.CommodityMsgH\003\210\001\001\0220\n\007country\030" +
      "\005 \001(\0162\032.chi.base.proto.CountryMsgH\004\210\001\001\022\023" +
      "\n\006userId\030\006 \001(\tH\005\210\001\001\022\026\n\tcreatedAt\030\007 \001(\003H\006" +
      "\210\001\001\022\025\n\010timeCost\030\010 \001(\005H\007\210\001\001B\005\n\003_idB\013\n\t_qu" +
      "antityB\010\n\006_priceB\014\n\n_commodityB\n\n\010_count" +
      "ryB\t\n\007_userIdB\014\n\n_createdAtB\013\n\t_timeCost" +
      "B\033\n\016chiw.spc.protoB\007OrderPBP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          chiw.spc.proto.CountryPB.getDescriptor(),
          chiw.spc.proto.CommodityPB.getDescriptor(),
        });
    internal_static_chi_base_proto_OrderMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chi_base_proto_OrderMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chi_base_proto_OrderMsg_descriptor,
        new java.lang.String[] { "Id", "Quantity", "Price", "Commodity", "Country", "UserId", "CreatedAt", "TimeCost", "Id", "Quantity", "Price", "Commodity", "Country", "UserId", "CreatedAt", "TimeCost", });
    chiw.spc.proto.CountryPB.getDescriptor();
    chiw.spc.proto.CommodityPB.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
