// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package chiw.spc.proto;

/**
 * Protobuf type {@code chi.base.proto.OrderMsg}
 */
public final class OrderMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chi.base.proto.OrderMsg)
    OrderMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderMsg.newBuilder() to construct.
  private OrderMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderMsg() {
    id_ = "";
    country_ = 0;
    userId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderMsg();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderMsg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            id_ = s;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            quantity_ = input.readInt32();
            break;
          }
          case 29: {
            bitField0_ |= 0x00000004;
            price_ = input.readFloat();
            break;
          }
          case 34: {
            chiw.spc.proto.CommodityMsg.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) != 0)) {
              subBuilder = commodity_.toBuilder();
            }
            commodity_ = input.readMessage(chiw.spc.proto.CommodityMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(commodity_);
              commodity_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();
            bitField0_ |= 0x00000010;
            country_ = rawValue;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000020;
            userId_ = s;
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            createdAt_ = input.readInt64();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000080;
            timeCost_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return chiw.spc.proto.OrderPB.internal_static_chi_base_proto_OrderMsg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return chiw.spc.proto.OrderPB.internal_static_chi_base_proto_OrderMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            chiw.spc.proto.OrderMsg.class, chiw.spc.proto.OrderMsg.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 2;
  private int quantity_;
  /**
   * <code>int32 quantity = 2;</code>
   * @return Whether the quantity field is set.
   */
  @java.lang.Override
  public boolean hasQuantity() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  public static final int PRICE_FIELD_NUMBER = 3;
  private float price_;
  /**
   * <code>float price = 3;</code>
   * @return Whether the price field is set.
   */
  @java.lang.Override
  public boolean hasPrice() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>float price = 3;</code>
   * @return The price.
   */
  @java.lang.Override
  public float getPrice() {
    return price_;
  }

  public static final int COMMODITY_FIELD_NUMBER = 4;
  private chiw.spc.proto.CommodityMsg commodity_;
  /**
   * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
   * @return Whether the commodity field is set.
   */
  @java.lang.Override
  public boolean hasCommodity() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
   * @return The commodity.
   */
  @java.lang.Override
  public chiw.spc.proto.CommodityMsg getCommodity() {
    return commodity_ == null ? chiw.spc.proto.CommodityMsg.getDefaultInstance() : commodity_;
  }
  /**
   * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
   */
  @java.lang.Override
  public chiw.spc.proto.CommodityMsgOrBuilder getCommodityOrBuilder() {
    return commodity_ == null ? chiw.spc.proto.CommodityMsg.getDefaultInstance() : commodity_;
  }

  public static final int COUNTRY_FIELD_NUMBER = 5;
  private int country_;
  /**
   * <code>.chi.base.proto.CountryMsg country = 5;</code>
   * @return Whether the country field is set.
   */
  @java.lang.Override public boolean hasCountry() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.chi.base.proto.CountryMsg country = 5;</code>
   * @return The enum numeric value on the wire for country.
   */
  @java.lang.Override public int getCountryValue() {
    return country_;
  }
  /**
   * <code>.chi.base.proto.CountryMsg country = 5;</code>
   * @return The country.
   */
  @java.lang.Override public chiw.spc.proto.CountryMsg getCountry() {
    @SuppressWarnings("deprecation")
    chiw.spc.proto.CountryMsg result = chiw.spc.proto.CountryMsg.valueOf(country_);
    return result == null ? chiw.spc.proto.CountryMsg.UNRECOGNIZED : result;
  }

  public static final int USERID_FIELD_NUMBER = 6;
  private volatile java.lang.Object userId_;
  /**
   * <code>string userId = 6;</code>
   * @return Whether the userId field is set.
   */
  @java.lang.Override
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>string userId = 6;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string userId = 6;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATEDAT_FIELD_NUMBER = 7;
  private long createdAt_;
  /**
   * <code>int64 createdAt = 7;</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>int64 createdAt = 7;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public long getCreatedAt() {
    return createdAt_;
  }

  public static final int TIMECOST_FIELD_NUMBER = 8;
  private int timeCost_;
  /**
   * <code>int32 timeCost = 8;</code>
   * @return Whether the timeCost field is set.
   */
  @java.lang.Override
  public boolean hasTimeCost() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>int32 timeCost = 8;</code>
   * @return The timeCost.
   */
  @java.lang.Override
  public int getTimeCost() {
    return timeCost_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, quantity_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeFloat(3, price_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getCommodity());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeEnum(5, country_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userId_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt64(7, createdAt_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeInt32(8, timeCost_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, quantity_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, price_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCommodity());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, country_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userId_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, createdAt_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, timeCost_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof chiw.spc.proto.OrderMsg)) {
      return super.equals(obj);
    }
    chiw.spc.proto.OrderMsg other = (chiw.spc.proto.OrderMsg) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasQuantity() != other.hasQuantity()) return false;
    if (hasQuantity()) {
      if (getQuantity()
          != other.getQuantity()) return false;
    }
    if (hasPrice() != other.hasPrice()) return false;
    if (hasPrice()) {
      if (java.lang.Float.floatToIntBits(getPrice())
          != java.lang.Float.floatToIntBits(
              other.getPrice())) return false;
    }
    if (hasCommodity() != other.hasCommodity()) return false;
    if (hasCommodity()) {
      if (!getCommodity()
          .equals(other.getCommodity())) return false;
    }
    if (hasCountry() != other.hasCountry()) return false;
    if (hasCountry()) {
      if (country_ != other.country_) return false;
    }
    if (hasUserId() != other.hasUserId()) return false;
    if (hasUserId()) {
      if (!getUserId()
          .equals(other.getUserId())) return false;
    }
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (getCreatedAt()
          != other.getCreatedAt()) return false;
    }
    if (hasTimeCost() != other.hasTimeCost()) return false;
    if (hasTimeCost()) {
      if (getTimeCost()
          != other.getTimeCost()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasQuantity()) {
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
    }
    if (hasPrice()) {
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPrice());
    }
    if (hasCommodity()) {
      hash = (37 * hash) + COMMODITY_FIELD_NUMBER;
      hash = (53 * hash) + getCommodity().hashCode();
    }
    if (hasCountry()) {
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + country_;
    }
    if (hasUserId()) {
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
    }
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreatedAt());
    }
    if (hasTimeCost()) {
      hash = (37 * hash) + TIMECOST_FIELD_NUMBER;
      hash = (53 * hash) + getTimeCost();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static chiw.spc.proto.OrderMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static chiw.spc.proto.OrderMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static chiw.spc.proto.OrderMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static chiw.spc.proto.OrderMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static chiw.spc.proto.OrderMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static chiw.spc.proto.OrderMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static chiw.spc.proto.OrderMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static chiw.spc.proto.OrderMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static chiw.spc.proto.OrderMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static chiw.spc.proto.OrderMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static chiw.spc.proto.OrderMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static chiw.spc.proto.OrderMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(chiw.spc.proto.OrderMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chi.base.proto.OrderMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chi.base.proto.OrderMsg)
      chiw.spc.proto.OrderMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return chiw.spc.proto.OrderPB.internal_static_chi_base_proto_OrderMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return chiw.spc.proto.OrderPB.internal_static_chi_base_proto_OrderMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              chiw.spc.proto.OrderMsg.class, chiw.spc.proto.OrderMsg.Builder.class);
    }

    // Construct using chiw.spc.proto.OrderMsg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommodityFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      quantity_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      price_ = 0F;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (commodityBuilder_ == null) {
        commodity_ = null;
      } else {
        commodityBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      country_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      userId_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      createdAt_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      timeCost_ = 0;
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return chiw.spc.proto.OrderPB.internal_static_chi_base_proto_OrderMsg_descriptor;
    }

    @java.lang.Override
    public chiw.spc.proto.OrderMsg getDefaultInstanceForType() {
      return chiw.spc.proto.OrderMsg.getDefaultInstance();
    }

    @java.lang.Override
    public chiw.spc.proto.OrderMsg build() {
      chiw.spc.proto.OrderMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public chiw.spc.proto.OrderMsg buildPartial() {
      chiw.spc.proto.OrderMsg result = new chiw.spc.proto.OrderMsg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.quantity_ = quantity_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.price_ = price_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        if (commodityBuilder_ == null) {
          result.commodity_ = commodity_;
        } else {
          result.commodity_ = commodityBuilder_.build();
        }
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.country_ = country_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.userId_ = userId_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.createdAt_ = createdAt_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.timeCost_ = timeCost_;
        to_bitField0_ |= 0x00000080;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof chiw.spc.proto.OrderMsg) {
        return mergeFrom((chiw.spc.proto.OrderMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(chiw.spc.proto.OrderMsg other) {
      if (other == chiw.spc.proto.OrderMsg.getDefaultInstance()) return this;
      if (other.hasId()) {
        bitField0_ |= 0x00000001;
        id_ = other.id_;
        onChanged();
      }
      if (other.hasQuantity()) {
        setQuantity(other.getQuantity());
      }
      if (other.hasPrice()) {
        setPrice(other.getPrice());
      }
      if (other.hasCommodity()) {
        mergeCommodity(other.getCommodity());
      }
      if (other.hasCountry()) {
        setCountry(other.getCountry());
      }
      if (other.hasUserId()) {
        bitField0_ |= 0x00000020;
        userId_ = other.userId_;
        onChanged();
      }
      if (other.hasCreatedAt()) {
        setCreatedAt(other.getCreatedAt());
      }
      if (other.hasTimeCost()) {
        setTimeCost(other.getTimeCost());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      chiw.spc.proto.OrderMsg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (chiw.spc.proto.OrderMsg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>int32 quantity = 2;</code>
     * @return Whether the quantity field is set.
     */
    @java.lang.Override
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>int32 quantity = 2;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>int32 quantity = 2;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      bitField0_ |= 0x00000002;
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantity = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000002);
      quantity_ = 0;
      onChanged();
      return this;
    }

    private float price_ ;
    /**
     * <code>float price = 3;</code>
     * @return Whether the price field is set.
     */
    @java.lang.Override
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>float price = 3;</code>
     * @return The price.
     */
    @java.lang.Override
    public float getPrice() {
      return price_;
    }
    /**
     * <code>float price = 3;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(float value) {
      bitField0_ |= 0x00000004;
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float price = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      bitField0_ = (bitField0_ & ~0x00000004);
      price_ = 0F;
      onChanged();
      return this;
    }

    private chiw.spc.proto.CommodityMsg commodity_;
    private com.google.protobuf.SingleFieldBuilderV3<
        chiw.spc.proto.CommodityMsg, chiw.spc.proto.CommodityMsg.Builder, chiw.spc.proto.CommodityMsgOrBuilder> commodityBuilder_;
    /**
     * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
     * @return Whether the commodity field is set.
     */
    public boolean hasCommodity() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
     * @return The commodity.
     */
    public chiw.spc.proto.CommodityMsg getCommodity() {
      if (commodityBuilder_ == null) {
        return commodity_ == null ? chiw.spc.proto.CommodityMsg.getDefaultInstance() : commodity_;
      } else {
        return commodityBuilder_.getMessage();
      }
    }
    /**
     * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
     */
    public Builder setCommodity(chiw.spc.proto.CommodityMsg value) {
      if (commodityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        commodity_ = value;
        onChanged();
      } else {
        commodityBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
     */
    public Builder setCommodity(
        chiw.spc.proto.CommodityMsg.Builder builderForValue) {
      if (commodityBuilder_ == null) {
        commodity_ = builderForValue.build();
        onChanged();
      } else {
        commodityBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
     */
    public Builder mergeCommodity(chiw.spc.proto.CommodityMsg value) {
      if (commodityBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
            commodity_ != null &&
            commodity_ != chiw.spc.proto.CommodityMsg.getDefaultInstance()) {
          commodity_ =
            chiw.spc.proto.CommodityMsg.newBuilder(commodity_).mergeFrom(value).buildPartial();
        } else {
          commodity_ = value;
        }
        onChanged();
      } else {
        commodityBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
     */
    public Builder clearCommodity() {
      if (commodityBuilder_ == null) {
        commodity_ = null;
        onChanged();
      } else {
        commodityBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
     */
    public chiw.spc.proto.CommodityMsg.Builder getCommodityBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getCommodityFieldBuilder().getBuilder();
    }
    /**
     * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
     */
    public chiw.spc.proto.CommodityMsgOrBuilder getCommodityOrBuilder() {
      if (commodityBuilder_ != null) {
        return commodityBuilder_.getMessageOrBuilder();
      } else {
        return commodity_ == null ?
            chiw.spc.proto.CommodityMsg.getDefaultInstance() : commodity_;
      }
    }
    /**
     * <code>.chi.base.proto.CommodityMsg commodity = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        chiw.spc.proto.CommodityMsg, chiw.spc.proto.CommodityMsg.Builder, chiw.spc.proto.CommodityMsgOrBuilder> 
        getCommodityFieldBuilder() {
      if (commodityBuilder_ == null) {
        commodityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            chiw.spc.proto.CommodityMsg, chiw.spc.proto.CommodityMsg.Builder, chiw.spc.proto.CommodityMsgOrBuilder>(
                getCommodity(),
                getParentForChildren(),
                isClean());
        commodity_ = null;
      }
      return commodityBuilder_;
    }

    private int country_ = 0;
    /**
     * <code>.chi.base.proto.CountryMsg country = 5;</code>
     * @return Whether the country field is set.
     */
    @java.lang.Override public boolean hasCountry() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.chi.base.proto.CountryMsg country = 5;</code>
     * @return The enum numeric value on the wire for country.
     */
    @java.lang.Override public int getCountryValue() {
      return country_;
    }
    /**
     * <code>.chi.base.proto.CountryMsg country = 5;</code>
     * @param value The enum numeric value on the wire for country to set.
     * @return This builder for chaining.
     */
    public Builder setCountryValue(int value) {
      bitField0_ |= 0x00000010;
      country_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.chi.base.proto.CountryMsg country = 5;</code>
     * @return The country.
     */
    @java.lang.Override
    public chiw.spc.proto.CountryMsg getCountry() {
      @SuppressWarnings("deprecation")
      chiw.spc.proto.CountryMsg result = chiw.spc.proto.CountryMsg.valueOf(country_);
      return result == null ? chiw.spc.proto.CountryMsg.UNRECOGNIZED : result;
    }
    /**
     * <code>.chi.base.proto.CountryMsg country = 5;</code>
     * @param value The country to set.
     * @return This builder for chaining.
     */
    public Builder setCountry(chiw.spc.proto.CountryMsg value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      country_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.chi.base.proto.CountryMsg country = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountry() {
      bitField0_ = (bitField0_ & ~0x00000010);
      country_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <code>string userId = 6;</code>
     * @return Whether the userId field is set.
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>string userId = 6;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userId = 6;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userId = 6;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>string userId = 6;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000020;
      userId_ = value;
      onChanged();
      return this;
    }

    private long createdAt_ ;
    /**
     * <code>int64 createdAt = 7;</code>
     * @return Whether the createdAt field is set.
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>int64 createdAt = 7;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public long getCreatedAt() {
      return createdAt_;
    }
    /**
     * <code>int64 createdAt = 7;</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(long value) {
      bitField0_ |= 0x00000040;
      createdAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 createdAt = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000040);
      createdAt_ = 0L;
      onChanged();
      return this;
    }

    private int timeCost_ ;
    /**
     * <code>int32 timeCost = 8;</code>
     * @return Whether the timeCost field is set.
     */
    @java.lang.Override
    public boolean hasTimeCost() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>int32 timeCost = 8;</code>
     * @return The timeCost.
     */
    @java.lang.Override
    public int getTimeCost() {
      return timeCost_;
    }
    /**
     * <code>int32 timeCost = 8;</code>
     * @param value The timeCost to set.
     * @return This builder for chaining.
     */
    public Builder setTimeCost(int value) {
      bitField0_ |= 0x00000080;
      timeCost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 timeCost = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeCost() {
      bitField0_ = (bitField0_ & ~0x00000080);
      timeCost_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chi.base.proto.OrderMsg)
  }

  // @@protoc_insertion_point(class_scope:chi.base.proto.OrderMsg)
  private static final chiw.spc.proto.OrderMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new chiw.spc.proto.OrderMsg();
  }

  public static chiw.spc.proto.OrderMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderMsg>
      PARSER = new com.google.protobuf.AbstractParser<OrderMsg>() {
    @java.lang.Override
    public OrderMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderMsg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public chiw.spc.proto.OrderMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

